#!/usr/bin/with-contenv bash

echo "clone git repo"
mkdir -p /app/TimePlayed
cd /app/TimePlayed/
git clone https://github.com/ExplodingPineapple/TimePlayed.git .
echo "install npm packages"
npm install discord.js mysql fast-levenshtein
echo "done"